### ISSUE TITLE
Location of pretrained weights

### ISSUE THREAD

**Issue by EliasVansteenkiste** [Cadene/pretrained-models.pytorch#1]
Hi Cadene,

Where can I download the pretrained weights?
The *.pth files you mention in the code?
I am looking for the inception-resnet-v2 model.

Thanks in advance,

**Comment by Cadene** [comment]
You don't have to download the pth files located in [inceptionresnetv2.py#L20](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/inceptionresnetv2.py#L20) by hand. This piece of code will do it automatically:

```python
import sys
sys.path.append('yourdir/pretrained-models.pytorch') # if needed
import pretrainedmodels

# Load Model
model_name = 'inceptionresnetv2'
model = pretrainedmodels.__dict__[model_name](num_classes=1001, pretrained='imagenet+background')
```

(Note that: `(num_classes=1000, pretrained='imagenet')` is not currently available, but will refer to the same pretrained parameters in the futur)
