### ISSUE TITLE
How to use this code on my own pretrsined model?

### ISSUE THREAD

**Issue by Maryames** [Cadene/pretrained-models.pytorch#100]
How can I use this code for evaluating my own pretrained model on PASCAL VOC ?I really need your help. I cannot find any pytorch code for voc classification and I need to evaluate my pretrained model with other papers while all of them used CAFFE code and my model is pth.
appreciate your help.

**Comment by Cadene** [comment]
You can extract features from a pretrained model on the VOC dataset using this code:
https://github.com/Cadene/pretrained-models.pytorch/blob/master/examples/voc2007_extract.py

(use pytorch 0.3)
