### ISSUE TITLE
Using model without pertained weights

### ISSUE THREAD

**Issue by arthursdays** [Cadene/pretrained-models.pytorch#131]
Hi,

I wonder is there a way to only use the model themselves without loading the pre-trained weights into them? Something like "model=pnasnet5large(num_classes=1000, pretrained='None')".

**Comment by Cadene** [comment]
`pretrained=None` should work

https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/inceptionresnetv2.py#L372

**Comment by arthursdays** [comment]
Oh yes! Thanksssss🙏
