### ISSUE TITLE
nasnetamobile TypeError: forward() missing 1 required positional argument: 'x_stem_0'

### ISSUE THREAD

**Issue by ChristophNeuner** [Cadene/pretrained-models.pytorch#132]
Hello,

I am trying to get the nasnetamobile to work with fastai.
Unfortunately this error occures, but I do not know how to fix it:

`TypeError                                 Traceback (most recent call last)
<ipython-input-12-13ecf5042fd9> in <module>
      3                      metrics=[accuracy, auc_score_1, auc_score_2],
      4                      ps=dropout,
----> 5                      pretrained='imagenet')

~/work/network/fastai/fastai/vision/learner.py in create_cnn(data, arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, **learn_kwargs)
     72     meta = cnn_config(arch)
     73     body = create_body(arch, pretrained, cut)
---> 74     nf = num_features_model(body) * 2
     75     head = custom_head or create_head(nf, data.c, lin_ftrs, ps=ps, bn_final=bn_final)
     76     model = nn.Sequential(body, head)

~/work/network/fastai/fastai/callbacks/hooks.py in num_features_model(m)
    117     sz = 64
    118     while True:
--> 119         try: return model_sizes(m, size=(sz,sz))[-1][1]
    120         except Exception as e:
    121             sz *= 2

~/work/network/fastai/fastai/callbacks/hooks.py in model_sizes(m, size)
    110     "Pass a dummy input through the model `m` to get the various sizes of activations."
    111     with hook_outputs(m) as hooks:
--> 112         x = dummy_eval(m, size)
    113         return [o.stored.shape for o in hooks]
    114 

~/work/network/fastai/fastai/callbacks/hooks.py in dummy_eval(m, size)
    105 def dummy_eval(m:nn.Module, size:tuple=(64,64)):
    106     "Pass a `dummy_batch` in evaluation mode in `m` with `size`."
--> 107     return m.eval()(dummy_batch(m, size))
    108 
    109 def model_sizes(m:nn.Module, size:tuple=(64,64))->Tuple[Sizes,Tensor,Hooks]:

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
     90     def forward(self, input):
     91         for module in self._modules.values():
---> 92             input = module(input)
     93         return input
     94 

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'x_stem_0'`

Thanks in advance!

Christoph

**Comment by PPPW** [comment]
Hi @ChristophNeuner, for fastai, in `create_body`, the model is converted to:

`nn.Sequential(*list(model.children())[:cut]`

However, `nn.Sequential` expects the modules to have exactly one argument in `forward`, but for NASNet, a few layers, such as `CellStem1`, take two arguments in forward. So we can't use it directly, we need to use the model as a whole then split it. I have a working [example here](https://github.com/PPPW/deep-learning-random-explore/blob/master/CNN_archs/cnn_archs.ipynb) for your reference.

**Comment by ChristophNeuner** [comment]
Thank you very much!
