### ISSUE TITLE
A small bug in `nasnetamobile.py` file

### ISSUE THREAD

**Issue by pyaf** [Cadene/pretrained-models.pytorch#137]
Hi, the default setting of `num_classes` for `nasnetamobile` model is 1000 [See here](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/nasnet_mobile.py#L32)

But the `NASNetAMobile` class is initialized with default num_classes as 1001 [here](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/nasnet_mobile.py#L523), which throws mismatch error of when num_classes is not explicitly specified during model initialization.

Would love to raise a PR to fix this, if you allow.

**Comment by Cadene** [comment]
Please go ahead! Thanks!!!
