### ISSUE TITLE
Toy example fails

### ISSUE THREAD

**Issue by nizhib** [Cadene/pretrained-models.pytorch#2]
Subj with `AssertionError: num_classes should be 1000, but is 1001`, because `imagenet` and 1001 classes are actually incosistent in the example.

BTW default params for `inceptionresnetv2` reprodeced in the toy example are fail-generating either.

**Comment by Cadene** [comment]
Yeap, I changed it in README but not in test/toy-example.py

It's done in https://github.com/Cadene/pretrained-models.pytorch/commit/7f378f98ad877a2398de7b52629e126d45c1b134
