### ISSUE TITLE
Modify NASNet

### ISSUE THREAD

**Issue by ahkarami** [Cadene/pretrained-models.pytorch#20]
Dear @Cadene,
Thank you for your fantastic repository. I want to modify NASNet (_i.e.,_ apply some minor modifications on NASNet by remove Dropout, add sigmoid layer at the end of net and etc.). I have implemented below code:

```
import torch
from torch.autograd import Variable
import torch.nn.functional as F
import torch.nn as nn
from nasnet import nasnetalarge

num_classes = 10

# *** Define Modified NASNet Class:
class ModifiedNASNet(nn.Module):
    def __init__(self, num_classes):
        super(ModifiedNASNet, self).__init__()

        original_model = nasnetalarge(num_classes=1000, pretrained='imagenet')

        # Everything except the last classifier:
        self.features = nn.Sequential(*list(original_model.children())[:-4])

        # Set number of features:
        num_feats = 4032

        # Plug our linear layer:
        self.classifier = nn.Sequential(nn.Linear(num_feats, num_classes))

    def forward(self, x):
        f = self.features(x)
        out = F.relu(f, inplace=True)
        out = F.avg_pool2d(out, kernel_size=11, stride=1, padding=0, ceil_mode=False, count_include_pad=True)
        out = out.view(out.size(0), -1) # Flatten
        out = self.classifier(out)
        out = F.sigmoid(out)
        return out

# *** test above class:
model = ModifiedNASNet(num_classes).cuda()
# print(model)
x = Variable(torch.randn(1, 3, 331, 331), volatile=True).cuda()
out = model(x)
print(out)

```

However, the following error has occurred:
`TypeError: forward() missing 1 required positional argument: 'x_stem_0'`
Would you please kindly help me to address this problem?

**Comment by emited** [comment]
In the nn.Sequential container, a module's output is taken as the next module's input. But `self.cell_stem1` takes input from both previous modules, `self.conv0` and `self.cell_stem_1`.  Try something like this:

```
import torch
from torch.autograd import Variable
import torch.nn.functional as F
from nasnet import NASNetALarge


class ModifiedNASNet(NASNetALarge):

    def classifier(self, x):
        out = F.relu(f, inplace=True)
        out = F.avg_pool2d(out, kernel_size=11, stride=1, padding=0, ceil_mode=False, count_include_pad=True)
        out = out.view(out.size(0), -1) # Flatten
        out = self.linear(out)
        out = F.sigmoid(out)
        return out        


# *** test above class:
model = ModifiedNASNet(num_classes).cuda()
# print(model)
x = Variable(torch.randn(1, 3, 331, 331), volatile=True).cuda()
out = model(x)
print(out)
```

**Comment by ahkarami** [comment]
Dear @emited,
Thank you very much. The problem has been solved.

**Comment by ClimbsRocks** [comment]
@emited I was hoping you could update the example above. I tried running it with the latest versions of PyTorch & this repo, and it seems the API has changed- I can't even get the imports to work. I tried a few obvious permutations, but to no avail.

Thanks in advance for the help!

**Comment by ClimbsRocks** [comment]
Hmmm, I think I've got it running, but I'd love your verification so future people know if this is the right pattern to use or not:

```
model_name = 'nasnetamobile'

model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')
model.eval()
original_model_features = list(model.children())[-1].in_features

model.avg_pool = nn.AdaptiveAvgPool2d(original_model_features)
model.last_linear = nn.Linear(original_model_features, len(class_names))
```

I think it's also very sensitive to input image size. I've gotten all kinds of shape mismatch errors when trying input sizes that worked with other models, but as soon as I tried 224x224, this model seemed to start running. Now I just need to figure out why (on first blush) it looks much slower than PyTorch's own ResNet18.

**Comment by emited** [comment]
Hello @ClimbsRocks. It has been a long time since I used this library... @Cadene ?
