### ISSUE TITLE
Pretrained data for nasnet not available on the servers

### ISSUE THREAD

**Issue by suvash** [Cadene/pretrained-models.pytorch#21]
https://github.com/Cadene/pretrained-models.pytorch/blob/da116f99e6326afad444de0f43008f9784fe60b1/pretrainedmodels/nasnet.py#L10

https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/nasnet.py#L19

@Cadene Thanks a lot for these pretrained models. I was trying to use nasnet in one of my experiments, when I realised that these files (linked above) don't exist on the server. Do I need to fetch these from somewhere else ?

I'm trying to figure this stuff out, so any tiny bit of help would be super. 🍻

**Comment by Cadene** [comment]
Oops, my bad. Available again.

**Comment by suvash** [comment]
Thanks tons again !
