### ISSUE TITLE
toy-example python2.7 compatibility

### ISSUE THREAD

**Issue by mtobeiyf** [Cadene/pretrained-models.pytorch#22]
Thank you for your great work! 🎉 

My environment was set based on Python 2.7, I met two problems while directly running toy-example.py

The first is: 
```python
Traceback (most recent call last):
  File "test/toy-example.py", line 9, in <module>
    import pretrainedmodels
  File "../pretrained-models.pytorch/pretrainedmodels/__init__.py", line 6, in <module>
    from .torchvision import *
  File "../pretrained-models.pytorch/pretrainedmodels/torchvision.py", line 1, in <module>
    import torchvision.models as models
ImportError: No module named models
```
I think this problem is caused by the name conflicts between the official torchvison and your `pretrainedmodels/torchvision.py`
so I simply rename `pretrainedmodels/torchvision.py` to `pretrainedmodels/torchvision2.py`, and modify the line `from .torchvision2 import *` in `pretrainedmodels/__init__.py` at the same time. 
It worked.

Then, another problem:
```python
Traceback (most recent call last):
  File "test/toy-example.py", line 35, in <module>
    transforms.Scale(round(max(model.input_size)*1.143)),
  File "/home/user/virtualenv/ENV/local/lib/python2.7/site-packages/torchvision/transforms.py", line 174, in __init__
    assert isinstance(size, int) or (isinstance(size, collections.Iterable) and len(size) == 2)
AssertionError
```
The argument passed to transformer `round(max(model.input_size)*1.143)` is not always an integer according to the python 2 [documentation](https://docs.python.org/2/library/functions.html#round)
By changing that line to
```python
transforms.Scale(int(round(max(model.input_size)*1.143))),
```
finally got the example running.

So, if you'd like, the code could improve its compatibility with Python 2.7.

Thank you so much! 😃

**Comment by Cadene** [comment]
https://github.com/Cadene/pretrained-models.pytorch/commit/9d0344a35c13826b4f51ab543acf040c21eed472

https://github.com/Cadene/pretrained-models.pytorch/commit/16230181c6d518f017cb73f5304fba7af274c69d

Done! :)
