### ISSUE TITLE
transforms.Scale seems to be deprecated

### ISSUE THREAD

**Issue by adamcasson** [Cadene/pretrained-models.pytorch#25]
Using torchvision 0.2.0

`UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.`

**Comment by Cadene** [comment]
Thanks for submitting this issue. It will be fixed soon :)

**Comment by Cadene** [comment]
@adamcasson Done! https://github.com/Cadene/pretrained-models.pytorch/commit/4417b9eace32f7b8b8ed335407451011852a8dc9

**Comment by ChenSQian** [comment]
Using torchvision 0.9.0, got the same error "The use of the transforms.Scale transform is deprecated", what could be the reasons for this issue?
