### ISSUE TITLE
NasNet

### ISSUE THREAD

**Issue by taylover-pei** [Cadene/pretrained-models.pytorch#29]
Sorry to bother you. I am a new one in NasNet. So, I have some questions about the architecture of the NasNet. I want to ask that what is the meaning of the CellStem0 and CellStem1 module? Is there some references to explain it? Looking forward to your reply.

**Comment by Cadene** [comment]
Hi @taylover-pei, sorry for the late answer.
Actually, I don't know any other reference than the [original paper](https://arxiv.org/abs/1707.07012) itself.
I would advise you to check other implementations (mine is a bit "naive"):

- https://github.com/tensorflow/models/tree/master/research/slim/nets/nasnet
- https://github.com/johannesu/NASNet-keras
- https://github.com/titu1994/Keras-NASNet
