### ISSUE TITLE
Upgrade `resnext101_*` to unified api

### ISSUE THREAD

**Issue by nizhib** [Cadene/pretrained-models.pytorch#3]
As for now model-returning functions have no `num_classes` param and model classes being returned don't have fields that are expected to be in the circumstances of unified behavior (`input_size`, `mean`, `std`, etc.)

**Comment by Cadene** [comment]
I am aware of this. Same for [wideresnet](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/wideresnet.py).

I would like to create a unified network architecture for all convnets with a Features module and a Classification module (not sequential as it is today).

**Comment by Cadene** [comment]
Unified `pretrained_settings` and function parameters done in https://github.com/Cadene/pretrained-models.pytorch/commit/aacc40b4ec5d4d6ba4788526fce30e20a9adb021
