### ISSUE TITLE
Inconsistent behavior of torchvision_models and other models on '.features'

### ISSUE THREAD

**Issue by xiadingZ** [Cadene/pretrained-models.pytorch#30]
when I use models such as inceptionv4, I can use
`model = nn.Sequential(model.features, nn.AvgPool2d(8, count_include_pad=False))`
to extract features of images, but when I use resnet152:
`model = nn.Sequential(model.features, nn.AvgPool2d(7, stride=1))`
it throws errors：
```
Traceback (most recent call last):
  File "prepro_feats.py", line 109, in <module>
    model.features, nn.AvgPool2d(7, stride=1))
  File "/home/xiading/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 50, in __init__
    self.add_module(str(idx), module)
  File "/home/xiading/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 139, in add_module
    torch.typename(module)))
TypeError: pretrainedmodels.models.torchvision_models.modify_resnets.<locals>.features is not a Module subclass
```

I hope these models can have a consitent behavior on their methods and attributes.

**Comment by Cadene** [comment]
@xiadingZ This is due to the fact that [InceptionV4 model.features](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/inceptionv4.py#L272) is a `nn.Sequential` whereas [Resnet152 model.features](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/torchvision_models.py#L300) is a function.

I would advise you for now to create a Wrapper class for what you want to achieve:

```python
class Model(nn.Module):
    def __init__(self, model, pooling):
        super(Model, self).__init__()
        self.model = model    
        self.pooling = pooling

    def forward(self, input):
        out = self.model.features(input)
        out = self.pooling(out)
        return out

inceptionv4 = Model(pretrainedmodels.inceptionv4(),
    nn.AvgPool2d(8, count_include_pad=False))

resnet152 = Model(pretrainedmodels.resnet152(),
    nn.AvgPool2d(7, stride=1))
```

**Comment by xiadingZ** [comment]
thanks. I think it would be better if your code can have consistent APIs, which can make it easier to use

**Comment by Cadene** [comment]
@xiadingZ Thanks for submitting this issue. I am aware of your concern, nevertheless the support of model.features as a nn.Module would take me a lot of time. For now, it is stated in the documentation that model.features should be used as method: https://github.com/Cadene/pretrained-models.pytorch#modelfeatures
