### ISSUE TITLE
default parameters of inception_v4 model conflicts

### ISSUE THREAD

**Issue by xiadingZ** [Cadene/pretrained-models.pytorch#31]
when I use `pretrainedmodels.inceptionv4()`, it will throw error:
```
AssertionError: num_classes should be 1000, but is 1000
```
I have to specify num_classes to 1000 or pretrained to imagenet+background. can't use the default parameters to construct

**Comment by Cadene** [comment]
Thanks for submitting this issue @xiadingZ 

I just fixed it https://github.com/Cadene/pretrained-models.pytorch/commit/f40b18090e9cd4a0eaa7f78504919a9314c41b57

Also, you can upgrade pretrainedmodels with pip now :)
```
pip install --upgrade pretrainedmodels
```
