### ISSUE TITLE
NasNet execution time

### ISSUE THREAD

**Issue by gngdb** [Cadene/pretrained-models.pytorch#35]
I was trying to adapt your model definition to include the CIFAR-10 and mobile version of the Nasnet network, ended up with the network here: https://github.com/gngdb/pytorch-cifar/blob/master/models/nasnet.py

I've checked the output is the same as the original version of your code, so I'm pretty sure the large version is correct. The only problem is I just tried to train the CIFAR-10 network and it's extremely slow. Have you noticed the execution time per image with the large version in this repository is slow? When I run it I'm getting about 4.5 seconds per image.

**Comment by Cadene** [comment]
Did you install the latest version of pytorch (0.3.x)?

```
print(torch.__version__)
```

**Comment by gngdb** [comment]
Ah, yes the server I was running it on had version `0.1` installed. On `0.3.0.post4` I get 600ms per minibatch, which is fair. One epoch of CIFAR-10 is now 4 minutes, so should be possible to train it. I suppose it's the separable convolutions being slow in the old version.

**Comment by Cadene** [comment]
@gngdb exactly :) best luck for your research
