### ISSUE TITLE
Error when loading pre-trained ResNeXt weights

### ISSUE THREAD

**Issue by snakers4** [Cadene/pretrained-models.pytorch#36]
After invoking ResNeXt from [here ](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/resnext.py) like this

`resnext = resnext101_32x4d(num_classes=1000, pretrained='imagenet')`

I get this error

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-3-83d6e919e255> in <module>()
> ----> 1 resnext = resnext101_32x4d(num_classes=1000, pretrained='imagenet')
> 
> <ipython-input-2-5550e9059627> in resnext101_32x4d(num_classes, pretrained)
>      81         settings = pretrained_settings['resnext101_32x4d'][pretrained]
>      82         assert num_classes == settings['num_classes'],             "num_classes should be {}, but is {}".format(settings['num_classes'], num_classes)
> ---> 83         model.load_state_dict(model_zoo.load_url(settings['url']))
>      84         model.input_space = settings['input_space']
>      85         model.input_size = settings['input_size']
> 
> /opt/conda/lib/python3.5/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict)
>     353             if name not in own_state:
>     354                 raise KeyError('unexpected key "{}" in state_dict'
> --> 355                                .format(name))
>     356             if isinstance(param, Parameter):
>     357                 # backwards compatibility for serialized parameters
> 
> KeyError: 'unexpected key "features.0.weight" in state_dict'

**Comment by snakers4** [comment]
@Cadene 
I believe I know what the problem is

This
```
model = ResNeXt101_64x4d(num_classes=1000)
model.state_dict().keys()
```
Outputs

> odict_keys(['last_linear.weight', 'last_linear.bias'])

I believe the problem lies in the fact that these [modules](https://github.com/Cadene/pretrained-models.pytorch/tree/master/pretrainedmodels/models/resnext_features) do not have their layers wrapped in a class inheriting from nn.module.

Am I right?

**Comment by snakers4** [comment]
@Cadene 

Looks like I more or less fixed it by doing this

1. Wrap your lambda layers like this

```
class resnext101_32x4d_features(nn.Module):

    def __init__(self):
        super(resnext101_32x4d_features, self).__init__()
        
        self.resnext101_32x4d_features = nn.Sequential( # Sequential,
        ....
        )
    def forward(self, input):
        x = self.resnext101_32x4d_features(input)
        return x    
```
2. Then change the import to
`from resnext_features.resnext101_32x4d_features import resnext101_32x4d_features`

3. Then invoke the resnext like this
```
class ResNeXt101_32x4d(nn.Module):

    def __init__(self, num_classes=1000):
        super(ResNeXt101_32x4d, self).__init__()
        self.num_classes = num_classes
        
        resnext = resnext101_32x4d_features()
        
        self.features = resnext.resnext101_32x4d_features
        self.avg_pool = nn.AvgPool2d((7, 7), (1, 1))
        self.last_linear = nn.Linear(2048, num_classes)

    def logits(self, input):
        x = self.avg_pool(input)
        x = x.view(x.size(0), -1)
        x = self.last_linear(x)
        return x

    def forward(self, input):
        x = self.features(input)
        x = self.logits(x)
        return x
```

**Comment by snakers4** [comment]
Also transfer learning people will surely appreciate such model layout

```
class resnext101_32x4d_features(nn.Module):

    def __init__(self):
        super(resnext101_32x4d_features, self).__init__()
        
        self.resnext101_32x4d_stem = nn.Sequential( # Sequential,
            nn.Conv2d(3,64,(7, 7),(2, 2),(3, 3),1,1,bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d((3, 3),(2, 2),(1, 1))
        )
            
        self.resnext101_32x4d_layer1 = nn.Sequential( # Sequential,

        )
        
        self.resnext101_32x4d_layer2 = nn.Sequential( # Sequential,
     
        )
        

        
    def forward(self, input):
        x = self.resnext101_32x4d_features(input)
        x = self.resnext101_32x4d_layer1(x)
        x = self.resnext101_32x4d_layer2(x)
        x = self.resnext101_32x4d_layer3(x)
        x = self.resnext101_32x4d_layer4(x)
        return x 
```

**Comment by Cadene** [comment]
Hi @snakers4,

Thanks for submitting this issue.
I try to load resnext that way and it works:
```python
import pretrainedmodels
net=pretrainedmodels.resnext101_32x4d(num_classes=1000, pretrained='imagenet')
```

I don't think you have the latest version of the pretrainedmodels module. You should probably reinstall:
```
pip uninstall pretrainedmodels
pip install pretrainedmodels
```
or
```
pip install --upgrade pretrainedmodels
```

Then:
```python
import pretrainedmodels
print(pretrainedmodels.__version__)
> '0.2.0'
```


Thanks for proposing this setup, but I don't have the time to do it right now.

**Comment by snakers4** [comment]
Ah, I see. I am not using the `pretrainedmodels` module, I am just taking your code and rewriting it every time. Now it makes sense.
