### ISSUE TITLE
NASNet Bug

### ISSUE THREAD

**Issue by haqishen** [Cadene/pretrained-models.pytorch#38]
hello

I've read the tensorflow version of nasnet and compared with your implementation.
I guess 

https://github.com/Cadene/pretrained-models.pytorch/blob/795f3710648c49792530c721d632a0ec0e7ed628/pretrainedmodels/models/nasnet.py#L565

should be
`x_cell_6 = self.cell_6(x_reduction_cell_0, x_cell_5)`

and

https://github.com/Cadene/pretrained-models.pytorch/blob/795f3710648c49792530c721d632a0ec0e7ed628/pretrainedmodels/models/nasnet.py#L574

should be 
`x_cell_12 = self.cell_12(x_reduction_cell_1, x_cell_11)`

isn't it?

**Comment by Cadene** [comment]
Thanks for submitting this issue. However, I don't think our implementation is wrong.

How did you see this? Does our implementation work better with these modifications?
