### ISSUE TITLE
DPN pretrained weights are not available

### ISSUE THREAD

**Issue by xfanplus** [Cadene/pretrained-models.pytorch#39]
all DualPathNetworks(DPN) pretrained weights are not available. I got "403 Forbidden" when i tried to download the following files:

http://data.lip6.fr/cadene/pretrainedmodels/dpn92_extra-b040e4a9b.pth
http://data.lip6.fr/cadene/pretrainedmodels/dpn68-66bebafa7.pth
http://data.lip6.fr/cadene/pretrainedmodels/dpn98-5b90dec4d.pth
etc.

**Comment by Cadene** [comment]
Sorry, I just fixed it. Does it work for you now?

**Comment by xfanplus** [comment]
@Cadene Yes, it works. Thanks for your excellent work!
