### ISSUE TITLE
Toy example incorrect answers

### ISSUE THREAD

**Issue by nizhib** [Cadene/pretrained-models.pytorch#4]
With toy example fixing with `(num_classes=1000, pretrained='imagenet')` the classes being returned are very strange:

* `inceptionresnetv2`
```
data/cat.jpg is a n03903868 pedestal, plinth, footstall
data/lena.jpg is a n03903868 pedestal, plinth, footstall
```
* `inceptionv4`
```
data/cat.jpg is a b'n01677366 common iguana, iguana, Iguana iguana'
data/lena.jpg is a b'n01677366 common iguana, iguana, Iguana iguana'
```
* `fbresnet152`
```
data/cat.jpg is a n01677366 common iguana, iguana, Iguana iguana
data/lena.jpg is a n01768244 trilobite
```

Synset neighbours of the returned classes don't fit either so it's not some form of +- 1 indexing problem.

**Comment by Cadene** [comment]
Yeap, you are very right. It is due to the missing `model.eval()` line :/

I just fixed it in https://github.com/Cadene/pretrained-models.pytorch/commit/c70599f7bae66058b1b6bdefebb04db17d838c04

Now all the models are saying it is a mud turtle! it could not be more true!

```
cadene@machine:~/distant/doc/pretrained-models.pytorch$ python test/toy-example.py -a fbresnet152 
data/lena.jpg is a b'n01667114 mud turtle'
cadene@machine:~/distant/doc/pretrained-models.pytorch$ python test/toy-example.py -a resnext101_32x4d 
data/lena.jpg is a b'n01667114 mud turtle'
cadene@machine:~/distant/doc/pretrained-models.pytorch$ python test/toy-example.py -a resnext101_64x4d
data/lena.jpg is a b'n01667114 mud turtle'
cadene@machine:~/distant/doc/pretrained-models.pytorch$ python test/toy-example.py -a inceptionv4
data/lena.jpg is a b'n01667114 mud turtle'
cadene@machine:~/distant/doc/pretrained-models.pytorch$ python test/toy-example.py -a inceptionresnetv2
data/lena.jpg is a b'n01667114 mud turtle'
```

**Comment by nizhib** [comment]
It seems like you are getting index for `imagenet_lsvrc_2015_synsets.txt` like in `models/inception`, not for your `imagenet_synsets.txt`.

**Comment by Cadene** [comment]
Yeap. It works now :)
You can try with cat.jpg and croco.jpg

https://github.com/Cadene/pretrained-models.pytorch/commit/570a22506963b004e79f543507dadc9959c3b438

**Comment by Cadene** [comment]
Thanks for the help
