### ISSUE TITLE
NASNeta_mobile

### ISSUE THREAD

**Issue by veronikayurchuk** [Cadene/pretrained-models.pytorch#41]
Hi @Cadene !
I rewrote https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/nasnet.py#L487 , so now two options are available NASNetALarge (6 @ 4032) and NASNetAMobile (4 @ 1056).
I can do a PR if it would be useful.

**Comment by achaiah** [comment]
Hey Veronika,

Out of curiosity, do you know what the size of a saved NASNetAMobile model turns out to be?

**Comment by Cadene** [comment]
That's so cool! Please do :)

**Comment by veronikayurchuk** [comment]
@achaiah it is 21M

**Comment by Cadene** [comment]
NASNetAMobile is available at https://github.com/wandering007/nasnet-pytorch

Thanks to @wandering007 !

https://github.com/Cadene/tensorflow-model-zoo.torch/issues/6

**Comment by veronikayurchuk** [comment]
Hi, all!

@Cadene I created a PR https://github.com/Cadene/pretrained-models.pytorch/pull/46 with ported weights to PyTorch.
The results  after porting are:  ** Acc@1 74.080 Acc@5 91.740**
