### ISSUE TITLE
AttributeError: 'Xception' object has no attribute 'fc'

### ISSUE THREAD

**Issue by lilhope** [Cadene/pretrained-models.pytorch#47]
It seems you have notice that in `xception`:
```
model.last_linear = model.fc
del model.fc
```
but in `xception.logist`:
`
output = self.fc(x)
`
It seems a bug?

**Comment by Cadene** [comment]
Thanks for submitting this issue. It was definitely a bug.

I just fixed it: https://github.com/Cadene/pretrained-models.pytorch/commit/f2ede774b06d2006c02cc6fb0148f719be560038

```
pip install --upgrade pretrainedmodels
```
