### ISSUE TITLE
Fail to load bninception

### ISSUE THREAD

**Issue by Redoblue** [Cadene/pretrained-models.pytorch#48]
Hello, when I try to load the `bninception` model with the following codes, something weird happens. I need some help, thanks.
```
model_name = 'nasnetalarge' # could be fbresnet152 or inceptionresnetv2
model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')
```

running the above code produces this:
```
anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py:514: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
```

**Comment by Cadene** [comment]
It is just a warning. It does not matter with the current last version of pytorch, but we should fix it.

**Comment by Redoblue** [comment]
Great! Thank you for your excellent work!

**Comment by poppingcode** [comment]
Hello, i want use bninception mode for my dataset(ucf101) ，so i change the code(bninception.py)---from num_classes=1000 to num_classes=101.but,when i load the pretrain-model.some wrong happen:

RuntimeError: While copying the parameter named last_linear.weight, whose dimensions in the model are torch.Size([101, 1024]) and whose dimensions in the checkpoint are torch.Size([1000, 1024]).

maybe i can do not make any changes，but when i Get this model（num_classes=1000），How to apply to the ucf101 model？
can you help me?.thanks.

**Comment by Redoblue** [comment]
@poppingcode I think there are two ways to realize this. 1. You can load all the parameters but the last fc layer, use a different linear layer and fine tune it with larger lr. 2. you can directly add an extra linear after the last fc layer and fine tune with larger lr. Good luck!

**Comment by Cadene** [comment]
@poppingcode 
You must load bn_inception with num_classes=1000, then you can adapt it to your number of classes:

```python
dim_feats = model.last_linear.in_features # =2048
nb_classes = 101
model.last_linear = nn.Linear(dim_feats, nb_classes)
output = model(input)
```

For more info: https://github.com/Cadene/pretrained-models.pytorch#modellast_linear
