### ISSUE TITLE
mean max pooling implement

### ISSUE THREAD

**Issue by lilhope** [Cadene/pretrained-models.pytorch#50]
Hi, 
    As states in http://arxiv.org/abs/1509.08985, the mean-max pooling could improve the model performance in testing stage. But I'm quite a newer with pytorch, and get no idea how to implement it? Could you give me some suggestion?

**Comment by Cadene** [comment]
I'm sorry, I could not find the time to answer.
I'm closing this issue.
Feel free to re-open if you still need it.
