### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by oavdeev** [Cadene/pretrained-models.pytorch#6]
Hi Remi!

Awesome work, would be great if you could clarify the license.

**Comment by Cadene** [comment]
Hi, thanks for your interest :)

I just added the License: https://github.com/Cadene/pretrained-models.pytorch/blob/master/LICENSE

Most of the model in this repo are from torchvision or tensorflow slim. InceptionV3 is available in torchvision as a porting from tensorflow. I suppose that they chose the right license, so I added exactly the same kind of license. However I am not an expert.
