### ISSUE TITLE
sth wrong with senet

### ISSUE THREAD

**Issue by he010103** [Cadene/pretrained-models.pytorch#60]
the line 193 shoule be change to `width = int(math.floor(planes * base_width / 64) * groups)`

**Comment by he010103** [comment]
my pytorch version is 0.3.1 and my python version is 2.7. When running the senet.py, width is 0 because  `(base_width / 64)` return 0 and the `math.floor` return float data.

**Comment by Cadene** [comment]
@he010103 We do not provide support for python2 for now, sorry :/

**Comment by Cadene** [comment]
Python 2.7 support is now provided.
