### ISSUE TITLE
BNInception does not ship in pytorch versions 0.2.0 and newer

### ISSUE THREAD

**Issue by adiser** [Cadene/pretrained-models.pytorch#70]
First of all, I would like to thank you for the awesome work for the community @yjxiong @Cadene

It's my first time raising an issue. Do guide me if you need anymore relevant information.

I happened to be experimenting with pytorch version 0.2.0 and 0.3.0. In which I used the BNInception pretrainedmodels ported by @yjxiong. 

While running model.load_state_dict(<params>). I encountered this error message:
        _While copying the parameter named "inception_4a_3x3_bn.weight", whose dimensions in the model are torch.Size([96]) and whose dimensions in the checkpoint are torch.Size([1, 96]).
        While copying the parameter named "inception_4a_3x3_bn.running_mean", whose dimensions in the model are torch.Size([96]) and whose dimensions in the checkpoint are torch.Size([1, 96]).
        While copying the parameter named "inception_4a_3x3_bn.bias", whose dimensions in the model are torch.Size([96]) and whose dimensions in the checkpoint are torch.Size([1, 96])._

It happened to all the layers.

It seems to me that the model only ships in pytorch versions older than 0.1.12. I tried using the same codebase and it worked seamlessly

**Comment by Mujtaba-Asif** [comment]
Traceback (most recent call last):
  File "/bninception.py", line 513, in <module>
    model = bninception()
  File "/bninception.py", line 504, in bninception
    model.load_state_dict(model_zoo.load_url(settings['url']))
  File "/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BNInception:
	size mismatch for conv1_7x7_s2_bn.weight: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.
	size mismatch for conv1_7x7_s2_bn.bias: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.
	size mismatch for conv1_7x7_s2_bn.running_mean: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.
	size mismatch for conv1_7x7_s2_bn.running_var: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.
	size mismatch for conv2_3x3_reduce_bn.weight: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.
	size mismatch for conv2_3x3_reduce_bn.bias: copying a param of torch.Size([64]) from checkpoint, where the shape is torch.Size([1, 64]) in current model.

**Comment by dichotomies** [comment]
@Mujtaba-Asif I've used the model for a research project and had to port it to PyTorch 0.4.1, see https://github.com/dichotomies/proxy-nca. You can find the weights [here](https://github.com/dichotomies/proxy-nca/blob/master/net/inception_v2_weights_pt04.pt).

@Cadene Do you think it would make sense to update the model here?

**Comment by Mujtaba-Asif** [comment]
Thanks @dichotomies the issue has been resolved here https://github.com/Cadene/pretrained-models.pytorch/issues/62 (Sorry I am not familiar with styling markdowns.

**Comment by Malathi15** [comment]
@Mujtaba-Asif @Mujtaba-Asif  I got the same size mismatch error.. Where I can find the weight file.. Also can't able to open the BNInception file in pretrain  folder
