### ISSUE TITLE
Anaconda installation not working

### ISSUE THREAD

**Issue by YugeTen** [Cadene/pretrained-models.pytorch#83]
Hi,

Just wondering if the anaconda installation link is going to be made available at some point? At the moment there seem to be some connection errors at the host.

Thanks for releasing the code by the way :+1: you don't need this from me but good work anyways

**Comment by Cadene** [comment]
https://conda.io/docs/user-guide/install/macos.html#installing-in-silent-mode

Seems to be working for me :)

**Comment by YugeTen** [comment]
My bad, thought with the "python3 with anaconda" link on your README was for this project as opposed to anaconda in general
