### ISSUE TITLE
InceptionResnetV2 - RuntimeError: invalid hash value

### ISSUE THREAD

**Issue by Trungmaster5** [Cadene/pretrained-models.pytorch#86]
I tried your InceptionResnetV2 model and got this error

> RuntimeError: invalid hash value (expected "520b38e4", got "00c0840425c822d2f0a0dd6b616b976f4de7f1d6fc5df56d398718d171ab54a1")

Could you please check it out ? 

The code I used was
`model = pretrainedmodels.inceptionresnetv2(num_classes= 1001, pretrained = 'imagenet+background’)`

Thank you for this awesome project.

**Comment by blueardour** [comment]
the urls of pretrained models for 'imagenet' and 'imagenet+background' are the same: http://data.lip6.fr/cadene/pretrainedmodels/inceptionresnetv2-520b38e4.pth

should they be different as the num_classes differs?

**Comment by Cadene** [comment]
imagenet+background is just to ease the use of the model for segmentation or localization tasks

**Comment by FindTheAnswer** [comment]
> I tried your InceptionResnetV2 model and got this error
> 
> > RuntimeError: invalid hash value (expected "520b38e4", got "00c0840425c822d2f0a0dd6b616b976f4de7f1d6fc5df56d398718d171ab54a1")
> 
> Could you please check it out ?
> 
> The code I used was
> `model = pretrainedmodels.inceptionresnetv2(num_classes= 1001, pretrained = 'imagenet+background’)`
> 
> Thank you for this awesome project.

Did you solve the question?
I have the same question .
The code I used was 
model_name = 'inceptionresnetv2' 
model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')

**Comment by Cadene** [comment]
Did you update the package?
```
pip install --update pretrainedmodels
```
