### ISSUE TITLE
'imagenet'['url'] in pretrained nasnet 

### ISSUE THREAD

**Issue by SherleyC** [Cadene/pretrained-models.pytorch#89]
isssue: 'imagenet' has the same 'url' with 'imagenet+background' 
pretrained_settings = {
    'nasnetalarge': {
        'imagenet': {
            'url': 'http://data.lip6.fr/cadene/pretrainedmodels/nasnetalarge-a1897284.pth',
            'input_space': 'RGB',
            'input_size': [3, 331, 331], # resize 354
            'input_range': [0, 1],
            'mean': [0.5, 0.5, 0.5],
            'std': [0.5, 0.5, 0.5],
            'num_classes': 1000
        },
        'imagenet+background': {
            'url': 'http://data.lip6.fr/cadene/pretrainedmodels/nasnetalarge-a1897284.pth',
            'input_space': 'RGB',
            'input_size': [3, 331, 331], # resize 354
            'input_range': [0, 1],
            'mean': [0.5, 0.5, 0.5],
            'std': [0.5, 0.5, 0.5],
            'num_classes': 1001
        }
    }
}

**Comment by Cadene** [comment]
It is not an issue. The tensorflow API for NasNet-A-Large comes with 1001 classes. The last classe (background) is used for object detection. I ported it quickly to be compatible with 1000 classes (image classification) or 1001 classes.
