### ISSUE TITLE
'HTTP Error 403: Forbidden' when downloading pretrained models

### ISSUE THREAD

**Issue by wu-hanqing** [Cadene/pretrained-models.pytorch#9]
Hi Cadene,

When I use your code as the example, 
```
model_name = 'bninception'
model = pretrainedmodels.__dict__[model_name](1000)
```
got an error: `urllib2.HTTPError: HTTP Error 403: Forbidden`.
If I open the url in browser, the message was 
`You don't have permission to access /~cadene/Downloads/pretrained-models.pytorch/bn_inception-9f5701afb96c8044.pth on this server.`.

So, is there something wrong with the server or the urls?

**Comment by Cadene** [comment]
The issue should be solved (read permission from outside my lab seemed to be missing).

http://webia.lip6.fr/~cadene/Downloads/pretrained-models.pytorch/bn_inception-9f5701afb96c8044.pth

**Comment by wu-hanqing** [comment]
Thanks for the permission.
