### ISSUE TITLE
Init pretrained densenet key error

### ISSUE THREAD

**Issue by wvinzh** [Cadene/pretrained-models.pytorch#92]
`
import pretrainedmodels`
`model_name = 'densenet121' `
`model = pretrainedmodels.__dict__[model_name](num_classes=1000, pretrained='imagenet')
`
when using such code to init a pretrained densenet, it occured a key error.
When I looked into the torchvision's densenet model code, I found you missed [such lines](https://github.com/pytorch/vision/blob/86001a871d3335046e2dca7715d9babf73e6956f/torchvision/models/densenet.py#L33-L41)

**Comment by Cadene** [comment]
Thanks, I will fix it soon.

**Comment by Cadene** [comment]
Fixed
