### ISSUE TITLE
http://data.lip6.fr/cadene/ is not available

### ISSUE THREAD

**Issue by dkozlov** [Cadene/pretrained-models.pytorch#95]
http://data.lip6.fr/cadene/ is not available

**Comment by dkozlov** [comment]
http://data.lip6.fr/cadene/ still not available

**Comment by Cadene** [comment]
@dkozlov

**Comment by dkozlov** [comment]
For example, try to download http://data.lip6.fr/cadene/pretrainedmodels/fbresnet152-2e20f6b4.pth from your desktop

**Comment by dkozlov** [comment]
Ok, it seems that it is my networking issues
